import { Metadata } from "next";

export const metatdata: Metadata = {
  title: "DM Tools",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <main>{children}</main>
    </>
  );
}
