import Head from "next/head";
import Container from "react-bootstrap/Container";
import NavigationHeader from "../NavigationHeader";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>DM Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationHeader></NavigationHeader>
      <main>{children}</main>
    </>
  );
}
